name: CI Espressif

on:
  push:
    branches: [feat/BME280-integration]
  pull_request:
    branches: [feat/BME280-integration]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Create sdkconfig.defaults for CI
        run: |
          cat > sdkconfig.defaults << 'EOF'
          CONFIG_WIFI_SSID="${{ secrets.WIFI_SSID }}"
          CONFIG_WIFI_PASSWORD="${{ secrets.WIFI_PASSWORD }}"
          CONFIG_MQTT_BROKER_URL="${{ secrets.MQTT_BROKER_URL }}"
          CONFIG_MQTT_USERNAME="${{ secrets.MQTT_USERNAME }}"
          CONFIG_MQTT_PASSWORD="${{ secrets.MQTT_PASSWORD }}"
          CONFIG_WIFI_MANAGER_MAX_RETRY=5
          EOF

      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.5.3
          target: esp32c3
          path: '.'